export enum SaleOrderBlingStatus {
  EM_ABERTO = 'EM_ABERTO',
  EM_DIGITACAO = 'EM_DIGITACAO',
  VENDA_AGENCIADA = 'VENDA_AGENCIADA',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  CANCELADO = 'CANCELADO',
  ATENDIDO = 'ATENDIDO',
}
